name: Build & Publish Release APK

on:
  push
  


jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.keystore }}
          keystore_password: ${{ secrets.keystore_password }}
          key_alias: ${{ secrets.key_alias }}
          key_password: ${{ secrets.key_password }}
    
